#include <SDL/SDL.h>
#include <SDL/SDL_image.h>
#include <SDL/SDL_mixer.h>
#include <stdio.h>
#include <stdlib.h>
#include "header.h"
#include "background.h"
#include "enigme.h"
#include "perso.h"
#include "minimap.h"
#include "ennemi.h"
